name: core
description: A new Flutter package project.
version: 0.0.1
homepage: null
publish_to: 'none'

environment:
  sdk: '>=2.16.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  about:
    path: ../about
  bloc: ^8.0.3
  bloc_test: ^9.0.3
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_rating_bar: ^4.0.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  http_certificate_pinning: ^2.0.4
  path_provider: ^2.0.2
  rxdart: ^0.27.3
  search:
    path: ../search
  sqflite: ^2.0.2+1

dev_dependencies:
  build_runner: ^2.0.4
  # flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
# - assets/cert/certificate.pem

#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
